### PR TITLE
Add `Virtualenv` and `Pexify` cmdclasses...

### PR DESCRIPTION
**Pull request by sixninetynine**
- Added a 'virtualenv' setuptools command class
- Added a 'pexify' setuptools command class
- Added some new deps (newer pip, wheel, pex)
- Converted module code to 4 space indents.
- Put helpers into their own submodule
- A few other style nitpicks

I did happen to notice some errors in the code, such as line 135-136, I added TODOs there.

### CODE REVIEW

**Comment by sixninetynine** [comment]
fwiw, this failure is unrelated to my change

**Comment by bringhurst** [comment]
> fwiw, this failure is unrelated to my change

Yeah... it hasn't had a successful build yet. Maybe after a few more commits.

**Comment by bringhurst** [comment]
Going to close this since most of the code that it applies to has been rewritten.

**Comment by sixninetynine** [comment]
:(

**Comment by bringhurst** [comment]
Sorry @sixninetynine! It was a good commit, just too much code churn recently.

**Comment by sixninetynine** [comment]
@bringhurst it's ok, looks like the functionality I added here was rebased/copied into a few of @toddpalino's PRs.

**Pull request closed without merging**
